const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const Ajv2020 = require("ajv/dist/2020");
const designSystem = require("../LPL-Design-System");
const {
  DEV_ACTIVE_PATH,
  DEV_DATA_DIRECTORY,
  DEV_DESIGN_SYSTEM_NAME,
  DEV_SCRIPT_NAME,
  buildBundle,
  buildDevBootstrap,
  buildDevInstaller,
  buildDevMainSource,
  buildFixtureBundle,
} = require("../scripts/build-dev-installer");

const root = path.join(__dirname, "..");
const formalMainSource = fs.readFileSync(
  path.join(root, "LPL-Schedule.js"),
  "utf8"
);
assert.doesNotMatch(
  formalMainSource,
  /DEV BOOTSTRAP - generated by Installer-Dev/
);
assert.doesNotMatch(formalMainSource, /globalThis\.__LPL_SCHEDULE_DEV__\s*=/);
const formalRuntimeContext = {
  console,
  Set,
  args: { queryParameters: {}, widgetParameter: "dev:ewc-priority" },
  importModule(name) {
    assert.equal(name, "LPL-Design-System");
    return designSystem;
  },
};
vm.runInNewContext(
  formalMainSource.replace(
    /await main\(\);\s*$/,
    "globalThis.__formalRuntimeTestApi = { IS_DEV, devFixtureKey };"
  ),
  formalRuntimeContext,
  { filename: "LPL-Schedule.js" }
);
assert.equal(formalRuntimeContext.__formalRuntimeTestApi.IS_DEV, false);
assert.equal(formalRuntimeContext.__formalRuntimeTestApi.devFixtureKey(), null);
const formalInstallerSource = fs.readFileSync(
  path.join(root, "Installer.js"),
  "utf8"
);
assert.doesNotMatch(formalInstallerSource, /Installer-Dev|LPL Schedule DEV/);
buildDevInstaller();
const installerSource = fs.readFileSync(
  path.join(root, "Installer-Dev.js"),
  "utf8"
);
const installerContext = {};
vm.runInNewContext(
  installerSource.replace(
    /await main\(\);\s*$/,
    "globalThis.__devInstallerTestApi = { BUNDLE, installBundle };"
  ),
  installerContext,
  { filename: "Installer-Dev.js" }
);
const installedBundle = JSON.parse(
  JSON.stringify(installerContext.__devInstallerTestApi.BUNDLE)
);
const currentBundle = buildBundle();

assert.equal(installedBundle.version, "3.1.0");
assert.equal(installedBundle.scriptName, DEV_SCRIPT_NAME);
assert.equal(installedBundle.designSystemName, DEV_DESIGN_SYSTEM_NAME);
assert.equal(installedBundle.dataDirectory, DEV_DATA_DIRECTORY);
assert.deepEqual(Object.keys(installedBundle.scripts).sort(), [
  "LPL Schedule DEV.js",
  "LPL-Design-System-DEV.js",
]);
assert.equal(
  installedBundle.scripts["LPL Schedule DEV.js"],
  buildDevMainSource()
);
const generatedDevMain = installedBundle.scripts["LPL Schedule DEV.js"];
assert.match(generatedDevMain, /DEV BOOTSTRAP - generated by Installer-Dev/);
assert.match(generatedDevMain, /enabled: true/);
assert.match(generatedDevMain, /version: "3\.1\.0"/);
assert.match(generatedDevMain, /fixture: ""/);
assert.match(generatedDevMain, /\/\/ MAIN SOURCE/);
assert.doesNotMatch(
  generatedDevMain,
  /globalThis\.__LPL_SCHEDULE_DEV__\s*=\s*\{\s*\}/
);
assert.equal(
  generatedDevMain.indexOf("DEV BOOTSTRAP") <
    generatedDevMain.indexOf("// MAIN SOURCE"),
  true
);
assert.equal(buildDevBootstrap().includes("enabled: true"), true);
assert.equal(
  installedBundle.scripts["LPL-Design-System-DEV.js"],
  fs.readFileSync(path.join(root, "LPL-Design-System.js"), "utf8")
);
assert.equal(
  installedBundle.dataFiles["active.json"],
  fs.readFileSync(DEV_ACTIVE_PATH, "utf8")
);
const devActive = JSON.parse(installedBundle.dataFiles["active.json"]);
assert.deepEqual(
  devActive,
  JSON.parse(fs.readFileSync(path.join(root, "data", "active.json"), "utf8"))
);
assert.equal(
  installedBundle.dataFiles["active.json"],
  fs.readFileSync(path.join(root, "data", "active.json"), "utf8")
);
assert.equal(
  installedBundle.scripts["LPL Schedule DEV.js"].includes(
    "raw.githubusercontent.com/braziliany/LPL-Scriptable/main"
  ),
  true
);
assert.doesNotMatch(
  installedBundle.scripts["LPL Schedule DEV.js"],
  /dev-local:\/\/LPL-Schedule-DEV/
);
assert.match(installerSource, /lpl-schedule-dev-cache\.json/);
assert.doesNotMatch(installerSource, /LPL Schedule Installer/);
assert.equal(
  currentBundle.scripts["LPL Schedule DEV.js"],
  buildDevMainSource()
);

const fixtures = buildFixtureBundle();
assert.equal(
  fixtures["lpl-playoffs.json"].active.tournament.id,
  "lpl-2026-split3-playoffs"
);
assert.equal(fixtures["ewc-priority.json"].active.tournament.id, "ewc-2026");
assert.equal(
  fixtures["ewc-priority.json"].active.selectionReason,
  "SMART_TODAY_MATCHES"
);
assert.equal(
  fixtures["ewc-priority.json"].routerSelectionReason,
  "SMART_TODAY_PRIORITY"
);
assert.equal(fixtures["ewc-priority.json"].scenario.mode, "SMART");
assert.equal(
  fixtures["ewc-priority.json"].scenario.tournaments.find(
    (tournament) => tournament.shortName === "EWC 2026"
  ).priority >
    fixtures["ewc-priority.json"].scenario.tournaments.find(
      (tournament) => tournament.shortName === "LPL PLAYOFFS"
    ).priority,
  true
);
assert.equal(
  Object.values(fixtures["ewc-priority.json"].scenario.schedules).every(
    (item) => item.matches[0].startTime.startsWith("2026-07-18")
  ),
  true
);
assert.equal(
  fixtures["worlds.json"].active.tournament.shortName,
  "WORLDS 2026"
);
assert.equal(fixtures["worlds.json"].active.matches[0].left, "BLG");
assert.equal(fixtures["worlds.json"].active.matches[0].right, "T1");
assert.equal(fixtures["worlds.json"].active.matches[0].matchType, "BO1");
assert.equal(fixtures["worlds.json"].active.matches[0].stage, "瑞士轮");
assert.equal(
  new Date(fixtures["stale-remote.json"].now).getTime() -
    new Date(fixtures["stale-remote.json"].active.generatedAt).getTime() >=
    72 * 60 * 60 * 1000,
  true
);
assert.equal(
  fixtures["stale-remote.json"].upstreamUpdatedAt,
  fixtures["stale-remote.json"].active.sourceUpdatedAt
);
assert.equal(fixtures["stale-remote.json"].active.tournament.season, "2026");
assert.equal(
  fixtures["stale-remote.json"].active.matches.every(
    (match) =>
      match.tournamentId === fixtures["stale-remote.json"].active.tournament.id
  ),
  true
);

const readJson = (relativePath) =>
  JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8"));
const ajv = new Ajv2020({ allErrors: true, strict: true });
ajv.addSchema(readJson("data/match.schema.json"));
ajv.addSchema(readJson("data/tournaments.schema.json"));
const validateActive = ajv.compile(readJson("data/active.schema.json"));
for (const [name, fixture] of Object.entries(fixtures)) {
  assert.equal(
    validateActive(fixture.active),
    true,
    `${name}: ${ajv.errorsText(validateActive.errors)}`
  );
}

const devRuntimeLogs = [];
const devMainContext = {
  console: {
    log(message) {
      devRuntimeLogs.push(String(message));
    },
    warn: console.warn,
    error: console.error,
  },
  Set,
  config: { runsInWidget: true, widgetFamily: "medium" },
  args: {
    queryParameters: {},
    widgetParameter: "dev:worlds",
  },
  importModule(name) {
    assert.equal(name, DEV_DESIGN_SYSTEM_NAME);
    return designSystem;
  },
};
devMainContext.Request = class {
  constructor(url) {
    assert.match(
      url,
      /^https:\/\/raw\.githubusercontent\.com\/braziliany\/LPL-Scriptable\/main\//
    );
  }

  async loadJSON() {
    return devActive;
  }
};
const iCloudFiles = new Map(
  Object.entries(installedBundle.dataFiles).map(([name, content]) => [
    `/icloud/${DEV_DATA_DIRECTORY}/data/${name}`,
    content,
  ])
);
const localFiles = new Map();
const fileManager = (files, documents) => ({
  documentsDirectory: () => documents,
  joinPath: (directory, name) => `${directory}/${name}`,
  fileExists: (file) => files.has(file),
  isFileDownloaded: () => true,
  async downloadFileFromiCloud() {},
  readString: (file) => files.get(file),
  writeString: (file, content) => files.set(file, content),
});
devMainContext.FileManager = {
  iCloud: () => fileManager(iCloudFiles, "/icloud"),
  local: () => fileManager(localFiles, "/local"),
};
devMainContext.Timer = {
  schedule(seconds, repeat, callback) {
    assert.equal(seconds >= 0, true);
    assert.equal(repeat, false);
    const handle = setTimeout(callback, seconds);
    return { invalidate: () => clearTimeout(handle) };
  },
};
devMainContext.WebView = class {
  async loadURL(url) {
    assert.match(url, /^https:\/\//);
  }

  async evaluateJavaScript() {
    return fixtures["stale-remote.json"].officialPageText;
  }
};
vm.runInNewContext(
  installedBundle.scripts["LPL Schedule DEV.js"].replace(
    /await main\(\);\s*$/,
    `globalThis.__devRuntimeTestApi = {
      IS_DEV,
      CACHE_FILE,
      SETTINGS_FILE,
      DATA_DIAGNOSTICS_FILE,
      devFixtureKey,
      devActiveResult,
      loadDevSchedule,
      loadSchedule,
      logoCacheFileName,
      matchSubtitle,
      tournamentFooterText,
    };`
  ),
  devMainContext,
  { filename: "LPL Schedule DEV.js" }
);
assert.equal(devMainContext.__devRuntimeTestApi.IS_DEV, true);
assert.deepEqual(
  JSON.parse(JSON.stringify(devMainContext.__LPL_SCHEDULE_DEV__)),
  {
    enabled: true,
    version: "3.1.0",
    fixture: "",
    designSystemModule: "LPL-Design-System-DEV",
    dataDirectory: "LPL-Schedule-DEV",
  }
);
assert.equal(
  devMainContext.__devRuntimeTestApi.CACHE_FILE,
  "lpl-schedule-dev-cache.json"
);
assert.equal(
  devMainContext.__devRuntimeTestApi.SETTINGS_FILE,
  "lpl-schedule-dev-settings.json"
);
assert.equal(
  devMainContext.__devRuntimeTestApi.DATA_DIAGNOSTICS_FILE,
  "lpl-schedule-dev-data-diagnostics.json"
);
assert.equal(devMainContext.__devRuntimeTestApi.devFixtureKey(), "worlds");
devMainContext.args.widgetParameter = "";
assert.equal(devMainContext.__devRuntimeTestApi.devFixtureKey(), null);
assert.equal(
  devMainContext.__devRuntimeTestApi.logoCacheFileName("BLG"),
  "lpl-team-logo-dev-BLG.png"
);

async function verifyRuntimeFixtures() {
  devMainContext.args.widgetParameter = "";
  const onlineResult = await devMainContext.__devRuntimeTestApi.loadSchedule();
  assert.equal(onlineResult.source, "GitHub Active");
  assert.equal(onlineResult.tournament.id, devActive.tournament.id);

  const fixtureCases = [
    ["dev:lpl-playoffs", "lpl-2026-split3-playoffs"],
    ["dev:ewc-priority", "ewc-2026"],
    ["dev:worlds", "worlds-2026"],
  ];
  for (const [parameter, tournamentId] of fixtureCases) {
    devMainContext.args.widgetParameter = parameter;
    const result = await devMainContext.__devRuntimeTestApi.loadDevSchedule();
    assert.equal(result.tournament.id, tournamentId);
    assert.match(result.source, /DEV/);
  }

  devMainContext.args.widgetParameter = "dev:worlds";
  const worldsResult =
    await devMainContext.__devRuntimeTestApi.loadDevSchedule();
  assert.equal(worldsResult.tournament.shortName, "WORLDS 2026");
  assert.equal(
    devMainContext.__devRuntimeTestApi.matchSubtitle(
      worldsResult.matches[0],
      new Date(fixtures["worlds.json"].now)
    ),
    "瑞士轮 · 未开始 · BO1"
  );
  assert.equal(
    devMainContext.__devRuntimeTestApi.tournamentFooterText(
      worldsResult.tournament
    ),
    "2026 全球总决赛 · 瑞士轮"
  );

  const freshClone = JSON.parse(
    JSON.stringify(fixtures["stale-remote.json"].active)
  );
  freshClone.generatedAt = fixtures["stale-remote.json"].now;
  freshClone.sourceUpdatedAt = fixtures["stale-remote.json"].now;
  assert.doesNotThrow(() =>
    devMainContext.__devRuntimeTestApi.devActiveResult(
      freshClone,
      new Date(fixtures["stale-remote.json"].now),
      "fresh control"
    )
  );

  devMainContext.args.widgetParameter = "dev:stale-remote";
  const staleResult =
    await devMainContext.__devRuntimeTestApi.loadDevSchedule();
  assert.equal(staleResult.source, "DEV LPL 官方页面");
  assert.equal(
    staleResult.selectionReason,
    "DEV_REMOTE_STALE_OFFICIAL_FALLBACK"
  );
  assert.equal(staleResult.matches.length > 0, true);
  const diagnostics = JSON.parse(
    localFiles.get("/local/lpl-schedule-dev-data-diagnostics.json")
  );
  assert.equal(diagnostics.mode, "dev:stale-remote");
  assert.deepEqual(
    diagnostics.attempts.map(({ status }) => status),
    ["failure", "attempted", "success"]
  );
  assert.match(diagnostics.attempts[0].message, /remote rejected: stale/);
  assert.equal(diagnostics.attempts[1].message, "official attempted");
  assert.equal(diagnostics.attempts[2].message, "official accepted");
  assert.equal(
    [
      "remote source:",
      "rejection reason: stale",
      "official fallback start",
      "official fallback result: accepted",
      "final source: DEV LPL 官方页面",
    ].every((entry) => devRuntimeLogs.some((line) => line.includes(entry))),
    true
  );

  devMainContext.args.widgetParameter = "dev:offline-cache";
  const offlineResult =
    await devMainContext.__devRuntimeTestApi.loadDevSchedule();
  assert.equal(offlineResult.source, "DEV local cache");
  assert.equal(offlineResult.selectionReason, "DEV_OFFLINE_CACHE_FIXTURE");
  const offlineDiagnostics = JSON.parse(
    localFiles.get("/local/lpl-schedule-dev-data-diagnostics.json")
  );
  assert.deepEqual(
    offlineDiagnostics.attempts.map(({ status }) => status),
    ["failure", "failure", "success"]
  );
  assert.match(
    offlineDiagnostics.attempts[0].message,
    /remote failed\/timeout/
  );
  assert.match(
    offlineDiagnostics.attempts[1].message,
    /official failed\/timeout/
  );
  assert.match(offlineDiagnostics.attempts[2].message, /cache accepted/);

  console.log("dev installer: ok");
}

verifyRuntimeFixtures().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
